# coding: utf-8

"""
    Tinxy API Documentation

    ### Steps    1. Install the Tinxy Mobile application    2. Login to application    3. Click on the setting icon (top left on android)    4. Click on API Token    5. Click on Get to token     6. Copy and save toke for usage in api  ## Notes Token should be sent via `Authorization: Bearer <token here>` header  

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tinxy_client.models.device import Device

class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Device:
        """Test Device
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Device`
        """
        model = Device()
        if include_optional:
            return Device(
                id = '',
                hub_id = 'asdasd12312jkh31kj23hkl12',
                user_id = 'asdasd12312jkh31kj23hkl12',
                enabled = True,
                devices = [
                    'Exhaust Fan'
                    ],
                device_types = [
                    'Fan'
                    ],
                switch_type = 'SWITCH',
                name = '',
                toggle_delay = 250,
                mqtt_password = '',
                type_id = tinxy_client.models.type_id.TypeId(
                    _id = '', 
                    primary = True, 
                    number_of_relays = 56, 
                    name = '', 
                    __v = 56, 
                    gtype = '', 
                    traits = [
                        'action.devices.traits.OnOff'
                        ], 
                    long_name = '2 Node Smart Switch', 
                    amazon_review_link = 'https://www.amazon.in/review/create-review/?asin=B08QF5WVN2', 
                    features = [
                        'SWITCH'
                        ], 
                    toggle_delay = 0, 
                    uuid_ref = tinxy_client.models.uuid_ref.uuidRef(), 
                    rf_code = 56, 
                    remote_codes = [
                        None
                        ], ),
                registration_date = '',
                firmware_version = 49,
                pairing_code = 12345678
            )
        else:
            return Device(
        )
        """

    def testDevice(self):
        """Test Device"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
