# coding: utf-8

"""
    Tinxy API Documentation

    ### Steps    1. Install the Tinxy Mobile application    2. Login to application    3. Click on the setting icon (top left on android)    4. Click on API Token    5. Click on Get to token     6. Copy and save toke for usage in api  ## Notes Token should be sent via `Authorization: Bearer <token here>` header  

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tinxy_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v2_devices_device_id_state_get(self) -> None:
        """Test case for v2_devices_device_id_state_get

        """
        pass

    def test_v2_devices_device_id_toggle_post(self) -> None:
        """Test case for v2_devices_device_id_toggle_post

        """
        pass

    def test_v2_devices_get(self) -> None:
        """Test case for v2_devices_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
