# coding: utf-8

"""
    Tinxy API Documentation

    ### Steps    1. Install the Tinxy Mobile application    2. Login to application    3. Click on the setting icon (top left on android)    4. Click on API Token    5. Click on Get to token     6. Copy and save toke for usage in api  ## Notes Token should be sent via `Authorization: Bearer <token here>` header  

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tinxy_client.models.device_state import DeviceState

class TestDeviceState(unittest.TestCase):
    """DeviceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceState:
        """Test DeviceState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceState`
        """
        model = DeviceState()
        if include_optional:
            return DeviceState(
                state = '',
                brightness = 0,
                status = 56
            )
        else:
            return DeviceState(
        )
        """

    def testDeviceState(self):
        """Test DeviceState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
