# coding: utf-8

"""
    Tinxy API Documentation

    ### Steps    1. Install the Tinxy Mobile application    2. Login to application    3. Click on the setting icon (top left on android)    4. Click on API Token    5. Click on Get to token     6. Copy and save toke for usage in api  ## Notes Token should be sent via `Authorization: Bearer <token here>` header  

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tinxy_client.models.type_id import TypeId
from typing import Optional, Set
from typing_extensions import Self

class Device(BaseModel):
    """
    Device
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    hub_id: Optional[StrictStr] = Field(default=None, description="Only for devices with hub", alias="hubId")
    user_id: Optional[StrictStr] = Field(default=None, description="Id of the user who owns the device", alias="userId")
    enabled: Optional[StrictBool] = None
    devices: Optional[List[StrictStr]] = None
    device_types: Optional[List[StrictStr]] = Field(default=None, alias="deviceTypes")
    switch_type: Optional[StrictStr] = Field(default=None, alias="switchType")
    name: Optional[StrictStr] = Field(default=None, description="The Name we set in App")
    toggle_delay: Optional[StrictInt] = Field(default=None, description="Toggle dealy in ms", alias="toggleDelay")
    mqtt_password: Optional[StrictStr] = Field(default=None, alias="mqttPassword")
    type_id: Optional[TypeId] = Field(default=None, alias="typeId")
    registration_date: Optional[StrictStr] = Field(default=None, alias="registrationDate")
    firmware_version: Optional[StrictInt] = Field(default=None, alias="firmwareVersion")
    pairing_code: Optional[StrictInt] = Field(default=None, alias="pairingCode")
    __properties: ClassVar[List[str]] = ["_id", "hubId", "userId", "enabled", "devices", "deviceTypes", "switchType", "name", "toggleDelay", "mqttPassword", "typeId", "registrationDate", "firmwareVersion", "pairingCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Device from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of type_id
        if self.type_id:
            _dict['typeId'] = self.type_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Device from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "hubId": obj.get("hubId"),
            "userId": obj.get("userId"),
            "enabled": obj.get("enabled"),
            "devices": obj.get("devices"),
            "deviceTypes": obj.get("deviceTypes"),
            "switchType": obj.get("switchType"),
            "name": obj.get("name"),
            "toggleDelay": obj.get("toggleDelay"),
            "mqttPassword": obj.get("mqttPassword"),
            "typeId": TypeId.from_dict(obj["typeId"]) if obj.get("typeId") is not None else None,
            "registrationDate": obj.get("registrationDate"),
            "firmwareVersion": obj.get("firmwareVersion"),
            "pairingCode": obj.get("pairingCode")
        })
        return _obj


