# coding: utf-8

"""
    Tinxy API Documentation

    ### Steps    1. Install the Tinxy Mobile application    2. Login to application    3. Click on the setting icon (top left on android)    4. Click on API Token    5. Click on Get to token     6. Copy and save toke for usage in api  ## Notes Token should be sent via `Authorization: Bearer <token here>` header  

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TypeId(BaseModel):
    """
    TypeId
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    primary: Optional[StrictBool] = None
    number_of_relays: Optional[StrictInt] = Field(default=None, alias="numberOfRelays")
    name: Optional[StrictStr] = None
    v: Optional[StrictInt] = Field(default=None, alias="__v")
    gtype: Optional[StrictStr] = None
    traits: Optional[List[StrictStr]] = None
    long_name: Optional[StrictStr] = None
    amazon_review_link: Optional[StrictStr] = Field(default=None, alias="amazonReviewLink")
    features: Optional[List[StrictStr]] = None
    toggle_delay: Optional[StrictInt] = Field(default=None, description="Toggle dealy in ms", alias="toggleDelay")
    uuid_ref: Optional[Dict[str, Any]] = Field(default=None, alias="uuidRef")
    rf_code: Optional[StrictInt] = Field(default=None, alias="rfCode")
    remote_codes: Optional[List[Dict[str, Any]]] = Field(default=None, alias="remoteCodes")
    __properties: ClassVar[List[str]] = ["_id", "primary", "numberOfRelays", "name", "__v", "gtype", "traits", "long_name", "amazonReviewLink", "features", "toggleDelay", "uuidRef", "rfCode", "remoteCodes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TypeId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TypeId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "primary": obj.get("primary"),
            "numberOfRelays": obj.get("numberOfRelays"),
            "name": obj.get("name"),
            "__v": obj.get("__v"),
            "gtype": obj.get("gtype"),
            "traits": obj.get("traits"),
            "long_name": obj.get("long_name"),
            "amazonReviewLink": obj.get("amazonReviewLink"),
            "features": obj.get("features"),
            "toggleDelay": obj.get("toggleDelay"),
            "uuidRef": obj.get("uuidRef"),
            "rfCode": obj.get("rfCode"),
            "remoteCodes": obj.get("remoteCodes")
        })
        return _obj


